# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matchNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teamNumber', models.IntegerField()),
                ('numberOfMatches', models.IntegerField()),
                ('maxScore', models.IntegerField()),
                ('minScore', models.IntegerField()),
                ('avgScore', models.IntegerField()),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
