# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avgScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='maxScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='minScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='numberOfMatches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamNumber',
            field=models.TextField(),
        ),
    ]
