# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160305_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamNumber',
            field=models.CharField(max_length=5),
        ),
    ]
