# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160305_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamNumber',
            field=models.IntegerField(),
        ),
    ]
