# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160305_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='defenseA',
            field=models.CharField(choices=[('P', 'Portcullis'), ('CF', 'Cheval de Frise')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseB',
            field=models.CharField(choices=[('M', 'Moat'), ('R', 'Ramparts')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseC',
            field=models.CharField(choices=[('D', 'Drawbridge'), ('SP', 'Sally Port')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseD',
            field=models.CharField(choices=[('RW', 'Rock Wall'), ('RT', 'Rough Terrain')], default='RW', max_length=2),
        ),
    ]
