# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160306_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batterShot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='courtyardShot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseACross',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseBCross',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseCCross',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseDCross',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defenseShot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='lowBarCross',
            field=models.IntegerField(default=0),
        ),
    ]
