# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160314_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
