# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160315_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=50, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamNumber',
            field=models.IntegerField(verbose_name='Team Number'),
        ),
    ]
