# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160315_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='alliance',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default='R', max_length=1, verbose_name='Alliance Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defenseACross',
            field=models.IntegerField(default=0, verbose_name='Defense A Crosses'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defenseBCross',
            field=models.IntegerField(default=0, verbose_name='Defense B Crosses'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defenseCCross',
            field=models.IntegerField(default=0, verbose_name='Defense C Crosses'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defenseDCross',
            field=models.IntegerField(default=0, verbose_name='Defense D Crosses'),
        ),
        migrations.AlterField(
            model_name='match',
            name='lowBarCross',
            field=models.IntegerField(default=0, verbose_name='Low Bar Crosses'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchNumber',
            field=models.IntegerField(verbose_name='Match Number'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Match Score'),
        ),
    ]
