# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160315_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rp',
            field=models.IntegerField(default=0, verbose_name='Ranking Points'),
        ),
    ]
